Repository gem09lo/PriceSlashTrack, pull requests merged in 2024-12, with the labels that each got.

#69 Updated email and schema scripts
  pipeline/email_notifier.py
  pipeline/test_email_notifier.py
  schema.sql
Labels: testing, pipeline, database

#66 #40 terraform script for streamlit dashboard
  pipeline/etl_docker_push.sh
  terraform/terraform-dashboard-ecr/main.tf
  terraform/terraform-dashboard-ecr/variables.tf
  terraform/terraform-dashboard-ecs/main.tf
  terraform/terraform-dashboard-ecs/variables.tf
Labels: terraform, visualisation

#71 Initial README for the pipeline folder.
  pipeline/README.md
Labels: documentation

#76 #65 Updated ERD
  diagrams/ERD.png
Labels: documentation, pipeline, visualisation

#78 READMEs for respective Terraform folders
  terraform/README.md
  terraform/terraform-dashboard-ecr/README.md
  terraform/terraform-dashboard-ecs/README.md
  terraform/terraform-etl-iterator/README.md
  terraform/terraform-rds/README.md
  terraform/terraform-subscriber-lambda/README.md
Labels: documentation

#77 #24 Streamlit Dashboard Beta
  dashboard.py
  database_connection.py
  requirements.txt
Labels: visualisation

#89 Added wireframe
  diagrams/wireframe.png
Labels: documentation, visualisation

#88 Making database folder and README.
  database/README.md
  database/connect.sh
  database/schema.sql
  database/seed_test_data.sh
  database/test_database.sql
Labels: documentation, database

#87 Added unsubscribe feature
  dashboard.py
Labels: visualisation

#94 Fixed dashboard error handling
  dashboard.py
Labels: bug

#80 #68-adding-amazon-to-extract
  .github/workflows/pytest.yml
  dashboard.py
  database/schema.sql
  database/test_database.sql
  pipeline/email_notifier.py
  pipeline/extract.py
  pipeline/load.py
  pipeline/test_extract.py
  pipeline/test_load.py
Labels: bug, pipeline, visualisation

#99 Updated About page on dashboard.
  dashboard.py
Labels: documentation, visualisation

#100 Reorganised dashboard folder.
  streamlit_dashboard/README.md
  streamlit_dashboard/dashboard.py
  streamlit_dashboard/database_connection.py
  streamlit_dashboard/requirements.txt
Labels: documentation, visualisation

#92 79 creating necessary docker files
  pipeline/remove_subscribers.dockerfile
  pipeline/remove_subscribers.py
  pipeline/remove_subscribers_requirements.txt
  pipeline/test_extract.py
  pipeline/upload_remove_subscribers_to_ecr.sh
  streamlit_dashboard.dockerfile
  streamlit_dashboard_upload.sh
  streamlit_requirements.txt
  terraform/terraform-dashboard-ecs/main.tf
  terraform/terraform-dashboard-sub-removal-ecr/README.md
  terraform/terraform-dashboard-sub-removal-ecr/main.tf
  terraform/terraform-dashboard-sub-removal-ecr/variables.tf
  terraform/terraform-subscriber-lambda/main.tf
  terraform/terraform-subscriber-lambda/variables.tf
Labels: pipeline, terraform

#111 Added image and description to dashboard
  database/test_database.sql
  streamlit_dashboard/dashboard.py
Labels: visualisation

#91 Checking quality of the unit test files to ensure consistency
  pipeline/load.py
  pipeline/test_connect_to_database.py
  pipeline/test_extract.py
  pipeline/test_load.py
  pipeline/test_remove_subscribers.py
  pipeline/test_transform.py
Labels: testing

#114 added scraping for debenhams
  database/test_database.sql
  pipeline/extract.py
Labels: enhancement, pipeline

#122 Added image and product description scraping for debenhams website
  database/test_database.sql
  pipeline/extract.py
  pipeline/test_extract.py
  pipeline/test_extract_html.txt
Labels: enhancement, visualisation

#127 Moving log out button to sidebar
  streamlit_dashboard/dashboard.py
Labels: visualisation

#124 Adding time filtering to charts on dashboard.
  streamlit_dashboard/dashboard.py
  streamlit_dashboard/database_connection.py
Labels: visualisation

#132 Reorganising dashboard
  streamlit_dashboard/dashboard.py
Labels: visualisation

#133 Updated email script
  pipeline/email_notifier.py
  pipeline/test_email_notifier.py
Labels: enhancement, pipeline

#135 Fixing accidental function call deletion.
  streamlit_dashboard/dashboard.py
Labels: bug, visualisation

#141 Standardising READMEs
  pipeline/README.md
  terraform/terraform-dashboard-ecs/README.md
  terraform/terraform-dashboard-sub-removal-ecr/README.md
  terraform/terraform-rds/README.md
  terraform/terraform-rds/main.tf
  terraform/terraform-rds/variables.tf
  terraform/terraform-subscriber-lambda/README.md
Labels: documentation

#146 added logo to diagrams
  diagrams/logo.png
Labels: documentation, visualisation

#142 increased pytest coverage of extract script
  pipeline/test_extract.py
  pipeline/test_load.py
  pipeline/test_remove_subscribers.py
Labels: testing, pipeline

#145 #121 new homepage
  streamlit_dashboard/.streamlit/config.toml
  streamlit_dashboard/dashboard.py
  streamlit_dashboard/homepage.py
  streamlit_dashboard/logo.png
  streamlit_dashboard/streamlit_dashboard.dockerfile
  terraform/terraform-etl-iterator/main.tf
  terraform/terraform-etl-iterator/variables.tf
Labels: enhancement, visualisation

#147 Fixing duplicate emails
  pipeline/email_notifier.py
  pipeline/test_email_notifier.py
Labels: bug

#119 added some tests for dashboard.py
  streamlit_dashboard/test_dashboard.py
  streamlit_dashboard/test_database_connection.py
Labels: testing
